# Sets up the GitHub action to automatically poll for data every 5 minutes
name: Disney Poller
on:
  schedule:
    - cron: '*/6 * * * *'  # Runs every 5 minutes
  workflow_dispatch:        # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        # This installs the packages you need into the cloud runner
        run: pip install requests pandas pytz

      - name: Run wait_time_scraper
        run: python wait_time_scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "DisneyBot"
          git config --global user.email "bot@github.com"
          git add wait_times.csv
          git commit -m "Update wait times for both parks" || exit 0
          git push
